### ISSUE TITLE
Is this repo. official implementation?

### ISSUE THREAD

**Issue by dragen1860** [JiaminRen/RandWireNN#1]
Hi, dear author,
  thanks for your great work and open source code. I wonder is this repo. the official implementation of original paper?  Thank you.
PS. It would be better if you can post your implementation performance benchmark in readme file.

**Comment by JiaminRen** [comment]
No, It's an unofficial repo. Training is in progress, and will be updated later.

**Comment by dragen1860** [comment]
Hi, Jiamin. How can you implement the paper in such a short time?
 I noticed the paper is released from arxiv on 2 April.
