### ISSUE TITLE
distributed training is stuck and very slow? 

### ISSUE THREAD

**Issue by xmengli** [JiaminRen/RandWireNN#7]
Hi, Jiamin. Many thanks for sharing your code. 
I run the train.sh and found that 
`broadcast_params(model)`
makes code stuck. 

When I remove this code, the training is still stuck by 
`       losses.update(reduced_loss.item(), input.size(0))
        top1.update(reduced_prec1.item(), input.size(0))
        top5.update(reduced_prec5.item(), input.size(0))`.

I used single node 8 GPUs for training. The training procedure is the same as you described. 
Do you know why this happens?

**Comment by JiaminRen** [comment]
Which pytorch version are you using?

**Comment by xmengli** [comment]
Thanks for prompt reply. Pytorch version:

`>>> torch.__version__
'1.0.0.dev20190110'`

**Comment by JiaminRen** [comment]
I only test pytorch=0.4.0, and you can change this version to try. I'll test version 1.0 when I'm free.

**Comment by xmengli** [comment]
When I create a new environment with pytorch 0.4, it still stuck. 

> certifi==2019.3.9
cffi==1.12.2
CVdevKit==1.0.0.dev1
decorator==4.4.0
mkl-fft==1.0.10
mkl-random==1.0.2
networkx==2.2
numpy==1.16.2
Pillow==6.0.0
protobuf==3.7.1
pycparser==2.19
PyYAML==5.1
six==1.12.0
tensorboardX==1.6
torch==0.4.0
torchvision==0.2.2.post3

**Comment by xmengli** [comment]
Could you please provide your requirement.txt file for reference.

**Comment by xmengli** [comment]
When I switch to another server, the problem goes away.  Thank you very much
