### ISSUE TITLE
Question on additive aggregation weight initialization

### ISSUE THREAD

**Issue by seungwonpark** [JiaminRen/RandWireNN#8]
Hi, I have a question about weight initialization of node's additive aggregation here.

At [model.py#L41](https://github.com/JiaminRen/RandWireNN/blob/master/model.py#L41), weights are initialized with `torch.ones`, not `torch.zeros`. This will make actual weights to be initialized with `0.7311`, not `0.5000`. Was it intended? (Though it won't affect much on training, I'm just curious about it.)

**Comment by JiaminRen** [comment]
I don't think it matters. A single parameter should be easy to optimize.

**Comment by seungwonpark** [comment]
Thanks for the comment.
